### ISSUE TITLE
problem bug?

### ISSUE THREAD

**Issue by cordoval** [stephpy/timeline-app#4]
@stephpy notice the top and bottom mixing of timelines, not sure why that is, i only created the first bottom actions for chuck but not for walter.

![screenshot 2014-08-27 00 53 37](https://cloud.githubusercontent.com/assets/328359/4055829/c126fbd2-2dae-11e4-87f1-991c5ee33313.png)

**Comment by stephpy** [comment]
I guess this is because walter white is aware of all actions about `vic` and `driving`.
